name: JIRA consistency

on: 
  issues:
    types: ['milestoned', 'demilestoned']
  pull_request:
    types: ['opened', 'edited', 'synchronize', 'reopened', 'closed']
  schedule:
    - cron: '5 * * * *'

jobs:
  jira_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: cchantep/probot-jira@ghaction-1.0.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_TOKEN_VALUE: 'personal_token'
          PERSONAL_TOKEN_USER: ${{ secrets.PERSONAL_TOKEN_VALUE }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: 'my.domain.tld'
          JIRA_USER: 'my-jira-login@foo.bar'
          JIRA_PROJECT_NAME: 'PRJ'
